### ISSUE TITLE
image.Image input

### ISSUE THREAD

**Issue by 89z** [carlogit/phash#3]
It would be helpful if function was available with image input, instead of `io.Reader`. This way users can crop image before hash if need be. Similar to:

https://pkg.go.dev/github.com/corona10/goimagehash#AverageHash

**Comment by carlogit** [comment]
It has been a while since I have not used this account. You might use the following "fork" https://github.com/ClessLi/phash, it adds the function you are looking for:
 
   func GetHashByIMG(image image.Image) string

That's the beauty of sharing code :).
